spring:
  application:
    name: run-ai-agent
  ai:
    dashscope:
      api-key: sk-c16df29724fa4331b27d8adba41cf1fe
      chat:
        options:
          model: qwen-max
search-api:
  api-key: C8CWLmLafqSgUS2Rd163a74M
server:
  port: 8123
  servlet:
    context-path: /api
#springdoc-openapi ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.run.runaiagent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

#logging:
#  level:
#    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug